"""Configuration and tuning constants"""

WIDTH = 800
HEIGHT = 600
FPS = 60

PLAYER_SPEED = 300  # pixels per second
PLAYER_WIDTH = 50
PLAYER_HEIGHT = 20

BULLET_SPEED = 500
ENEMY_ROWS = 4
ENEMY_COLS = 8
ENEMY_WIDTH = 40
ENEMY_HEIGHT = 24
ENEMY_H_SPACING = 10
ENEMY_V_SPACING = 16
